=head1 TODO for Dancer::Plugin::SimpleCRUD

=head2 Before release

=over 

=item Tidy up and refactor where possible.

It's a bit of a mess at the moment.

=item Understand Dancer's route prefix option

If called after using Dancer's prefix keyword, links to add/edit records will 
be broken, as it doesn't know that a prefix will be added.

=back

=head2 Later

=over

=item Pagination support on list page

Allow configurable pagination support on list page.


=item Searching on list page

Make it possible to search on the list page?

=item Output JS to make list table sortable?

Use sorttable or another JS solution to make the list page sortable, by clicking
on column headings?

=item Option to make the list page handler return template-ready params

Provide option to make list page handler return template-ready params instead of
plain HTML, for those who want to customise the page a lot more.

=item Support more databases

Refactor C<_find_columns()> to work in a DB-agnostic way, and support other
databases - PostgreSQL?  SQLite?  DBIC?

=item Show message when an entry has been created/edited/deleted

At the moment we just send the user back to the list page, we should probably
show a "Record {added,updated,deleted}" message to make it clear it was
successful.

=item Option to present form in facebox div?

Maybe add the option for the add/edit form to be presented within a "popup div"
using Facebox, rather than as a standalone page.  (When the form is submitted,
it could need to reload the list page afterwards, or we could allow that to be
done via an AJAX call too)

=item Automatic password confirmation

If we recognise a field as a password field, present a "Type your password
again" box, and add code to validate that the passwords match.
